### ISSUE TITLE
[BUG] Some `afcharts` functions do not work unless the package is loaded first

### ISSUE THREAD

**Issue by James-Osmond** [best-practice-and-impact/afcharts#28]
Running on v0.4.0. If I run a function such as `afcharts::scale_colour_discrete_af()` in isolation, I will get an error as follows:

```{r}
Error in af_palette(palette, reverse, palette_type = palette_type) : 
object 'af_colour_palettes' not found
```

However, if I make sure to load `afcharts` in my current R session first with `library(afcharts)`, everything will work as expected.

**Comment by lattaai10** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified R/data.R to export af_colour_values and af_colour_palettes objects, and removed globalVariables() from R/afcharts-package.R to ensure data objects are available without explicitly loading the package.

You can review changes in this commit: https://github.com/lattaai10/best-practice-and-impact-afcharts-28/commit/c75c771ac203e2fc855a9afe172a9a6a0cc564db.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
