### ISSUE TITLE
af_palette warning - "Using `main2` as only two colours are required."

### ISSUE THREAD

**Issue by Olivia-Box-Power** [best-practice-and-impact/afcharts#39]
af_palette can give the following warning - "Using `main2` as only two colours are required." Should this be a message instead? This would prevent generating warnings when running tests.

**Comment by Olivia-Box-Power** [comment]
@alice-hannah Any views?

**Comment by alice-hannah** [comment]
I think a message would be fine. I think the thought was that people should change their code to use `main2` instead of getting the message/warning every time. But actually, they'd get the warning/message even if just using `use_afcharts()` as the default palette is `main`. In short, I think using a message instead makes sense.

**Comment by Olivia-Box-Power** [comment]
Thanks @alice-hannah . I've converted it to a message.
